### ISSUE TITLE
Data Validation for User Input

### ISSUE THREAD

**Issue by jbean96** [jbean96/Mutation-Visualization#13]
It would be a good idea to have some sort of input validator that runs when a user uploads their mutation .json file to the web interface. This way if certain attributes are missing or have the wrong format we can provide a more useful message and also avoid unexpected crashes if something goes wrong.

**Comment by sainimma** [comment]
This is pretty low priority right?

**Comment by sainimma** [comment]
Resolve #15 as well to resolve this

**Comment by sainimma** [comment]
Resolved in #20
