### ISSUE TITLE
Disallow Mutants that are both Equivalent and Killed

### ISSUE THREAD

**Issue by jbean96** [jbean96/Mutation-Visualization#15]
By definition, I am 99% certain that a mutant that has been killed cannot be equivalent, otherwise how would it have been killed in the first place?

We should not allow the user to change a mutant to equivalent that has already been killed... potentially we should even note to users that they have killed & equivalent mutants if the data loaded to the application has a mutant that falls under that case.

**Comment by sainimma** [comment]
What if we just removed the "killed" field on the JSON? We could just use the length of the "killers" array to determine if a mutant was killed and then show switches accordingly...

**Comment by sainimma** [comment]
Fixing this in a PR I'm going to push in the morning. Basically, we shouldn't actually need the "killed" field in the JSON...we can use the length of the "killers" array to determine if a mutant has been killed. Thus we can mitigate error in how the JSON is filled. Then, we can only show the equivalent switch if there are no killers for the mutant

**Comment by sainimma** [comment]
I'll distribute the changes over multiple PRs for modularity

**Comment by jbean96** [comment]
Sounds good!

**Comment by sainimma** [comment]
Merging with #13
