### ISSUE TITLE
Filter and Color Options

### ISSUE THREAD

**Issue by ghost** [jbean96/Mutation-Visualization#17]
The ability to filter results in the table to view only certain mutants could help the user sift through large amounts of data. In addition, each row in the table (or maybe each 'true' and 'false' statement) could be colored to help indicate the type of mutant (equivalent, productive, etc.).

**Comment by sainimma** [comment]
Search/filter is already built in to the table.

**Comment by ghost** [comment]
There is a sort but not filter capability. However, this is a minor addition that can be held off for a later version.
