### ISSUE TITLE
Code section on mutant component incorrect

### ISSUE THREAD

**Issue by sainimma** [jbean96/Mutation-Visualization#3]
Code section should have the right line numbers next to each line and the mutated line should be highlighted

**Comment by jbean96** [comment]
I got the initial push of the change up there but I'll debug our `muupi` script to test some more of the line numbering stuff since that's screwing it up a little bit.

**Comment by sainimma** [comment]
I'm going to close this issue because the issue is now in our muupi and not our visualization.
