### ISSUE TITLE
Document JSON Structure

### ISSUE THREAD

**Issue by jbean96** [jbean96/Mutation-Visualization#9]
We need to document the JSON strucure that we expect for upload, add it to a separate page or the README and add a format checker to the uploading mechanism in order to provide useful error messages when parsing incorrect JSON.

**Comment by jbean96** [comment]
Documented in the README on b30a454e2a51cd4f1a3d4de791e4066d975fa915 but need to add a top-level page

**Comment by sainimma** [comment]
This looks done. Can the issue be closed?

**Comment by sainimma** [comment]
Closing the issue since it appears to be done.
